### ISSUE TITLE
Is this still being maintained

### ISSUE THREAD

**Issue by kittivelae** [isaaczafuta/whatapi#19]
Hi, I was just wondering if this is still being maintained? With the new API changes at RED I'd quite like to amend this to work with them and the new endpoints. However, I notice there are a few outstanding PR's that haven't been reviewed and the last commit was a couple of years ago. If this isn't being maintained anymore, would it be okay if I duplicated the repository and continued it under a new name, giving credit to you and the original module of course?

Cheers,
kittivelae

**Comment by kittivelae** [comment]
also i hope this was okay to do, im not really sure of the etiquette surrounding this, so sorry if this wasnt the done thing :)

**Comment by point-source** [comment]
Thanks for asking kittivelae! It looks like isaaczafuta just merged my open PRs that you were referring to. I have an in-progress implementation of RED's api key support on my branch here: https://github.com/point-source/whatapi/tree/api_key

I started it around the same time I made those PRs so I haven't tested it in the time since the official api rollout. I won't have time to do this for at least another week most likely. If you want to take over that PR, feel free to use my code if it helps. Thanks!

**Comment by isaaczafuta** [comment]
Hi, thanks or reaching out :)

I went ahead and addressed those outstanding PRs, and I'll push a point release shortly. I've been using this library for some personal projects, but it's currently just an extremely basic wrapper.

I've been wanting to develop it into a more opinionated library for the RED endpoints, and I think the additional endpoints means this is the perfect time to do it. I think your branch is along the right direction, so I'll definitely be looking at that as a base. I'll also be hanging out in #red-dev irc channel now if you'd like to chat :)
